#include "spk_keyboard.hpp"

namespace spk
{
	std::string toString(const Keyboard::Key &p_key)
	{
		switch (p_key)
		{
		case spk::Keyboard::Key::Backspace:
			return ("Backspace");
		case spk::Keyboard::Key::Tab:
			return ("Tab");
		case spk::Keyboard::Key::Clear:
			return ("Clear");
		case spk::Keyboard::Key::Return:
			return ("Return");
		case spk::Keyboard::Key::Shift:
			return ("Shift");
		case spk::Keyboard::Key::Control:
			return ("Control");
		case spk::Keyboard::Key::Alt:
			return ("Alt");
		case spk::Keyboard::Key::Pause:
			return ("Pause");
		case spk::Keyboard::Key::Capslock:
			return ("Capslock");
		case spk::Keyboard::Key::Escape:
			return ("Escape");
		case spk::Keyboard::Key::Convert:
			return ("Convert");
		case spk::Keyboard::Key::Non_convert:
			return ("Non_convert");
		case spk::Keyboard::Key::Accept:
			return ("Accept");
		case spk::Keyboard::Key::Mode_change:
			return ("Mode_change");
		case spk::Keyboard::Key::Space:
			return ("Space");
		case spk::Keyboard::Key::Prior:
			return ("Prior");
		case spk::Keyboard::Key::Next:
			return ("Next");
		case spk::Keyboard::Key::End:
			return ("End");
		case spk::Keyboard::Key::Home:
			return ("Home");
		case spk::Keyboard::Key::LeftArrow:
			return ("LeftArrow");
		case spk::Keyboard::Key::UpArrow:
			return ("UpArrow");
		case spk::Keyboard::Key::RightArrow:
			return ("RightArrow");
		case spk::Keyboard::Key::DownArrow:
			return ("DownArrow");
		case spk::Keyboard::Key::Select:
			return ("Select");
		case spk::Keyboard::Key::Print:
			return ("Print");
		case spk::Keyboard::Key::Execute:
			return ("Execute");
		case spk::Keyboard::Key::Snapshot:
			return ("Snapshot");
		case spk::Keyboard::Key::Insert:
			return ("Insert");
		case spk::Keyboard::Key::Delete:
			return ("Delete");
		case spk::Keyboard::Key::Help:
			return ("Help");
		case spk::Keyboard::Key::Key0:
			return ("Key0");
		case spk::Keyboard::Key::Key1:
			return ("Key1");
		case spk::Keyboard::Key::Key2:
			return ("Key2");
		case spk::Keyboard::Key::Key3:
			return ("Key3");
		case spk::Keyboard::Key::Key4:
			return ("Key4");
		case spk::Keyboard::Key::Key5:
			return ("Key5");
		case spk::Keyboard::Key::Key6:
			return ("Key6");
		case spk::Keyboard::Key::Key7:
			return ("Key7");
		case spk::Keyboard::Key::Key8:
			return ("Key8");
		case spk::Keyboard::Key::Key9:
			return ("Key9");
		case spk::Keyboard::Key::A:
			return ("A");
		case spk::Keyboard::Key::B:
			return ("B");
		case spk::Keyboard::Key::C:
			return ("C");
		case spk::Keyboard::Key::D:
			return ("D");
		case spk::Keyboard::Key::E:
			return ("E");
		case spk::Keyboard::Key::F:
			return ("F");
		case spk::Keyboard::Key::G:
			return ("G");
		case spk::Keyboard::Key::H:
			return ("H");
		case spk::Keyboard::Key::I:
			return ("I");
		case spk::Keyboard::Key::J:
			return ("J");
		case spk::Keyboard::Key::K:
			return ("K");
		case spk::Keyboard::Key::L:
			return ("L");
		case spk::Keyboard::Key::M:
			return ("M");
		case spk::Keyboard::Key::N:
			return ("N");
		case spk::Keyboard::Key::O:
			return ("O");
		case spk::Keyboard::Key::P:
			return ("P");
		case spk::Keyboard::Key::Q:
			return ("Q");
		case spk::Keyboard::Key::R:
			return ("R");
		case spk::Keyboard::Key::S:
			return ("S");
		case spk::Keyboard::Key::T:
			return ("T");
		case spk::Keyboard::Key::U:
			return ("U");
		case spk::Keyboard::Key::V:
			return ("V");
		case spk::Keyboard::Key::W:
			return ("W");
		case spk::Keyboard::Key::X:
			return ("X");
		case spk::Keyboard::Key::Y:
			return ("Y");
		case spk::Keyboard::Key::Z:
			return ("Z");
		case spk::Keyboard::Key::LeftWindows:
			return ("LeftWindows");
		case spk::Keyboard::Key::RightWindows:
			return ("RightWindows");
		case spk::Keyboard::Key::App:
			return ("App");
		case spk::Keyboard::Key::Sleep:
			return ("Sleep");
		case spk::Keyboard::Key::Numpad0:
			return ("Numpad0");
		case spk::Keyboard::Key::Numpad1:
			return ("Numpad1");
		case spk::Keyboard::Key::Numpad2:
			return ("Numpad2");
		case spk::Keyboard::Key::Numpad3:
			return ("Numpad3");
		case spk::Keyboard::Key::Numpad4:
			return ("Numpad4");
		case spk::Keyboard::Key::Numpad5:
			return ("Numpad5");
		case spk::Keyboard::Key::Numpad6:
			return ("Numpad6");
		case spk::Keyboard::Key::Numpad7:
			return ("Numpad7");
		case spk::Keyboard::Key::Numpad8:
			return ("Numpad8");
		case spk::Keyboard::Key::Numpad9:
			return ("Numpad9");
		case spk::Keyboard::Key::NumpadMultiply:
			return ("NumpadMultiply");
		case spk::Keyboard::Key::NumpadPlus:
			return ("NumpadPlus");
		case spk::Keyboard::Key::NumpadSeparator:
			return ("NumpadSeparator");
		case spk::Keyboard::Key::NumpadMinus:
			return ("NumpadMinus");
		case spk::Keyboard::Key::NumpadDecimal:
			return ("NumpadDecimal");
		case spk::Keyboard::Key::NumpadDivide:
			return ("NumpadDivide");
		case spk::Keyboard::Key::F1:
			return ("F1");
		case spk::Keyboard::Key::F2:
			return ("F2");
		case spk::Keyboard::Key::F3:
			return ("F3");
		case spk::Keyboard::Key::F4:
			return ("F4");
		case spk::Keyboard::Key::F5:
			return ("F5");
		case spk::Keyboard::Key::F6:
			return ("F6");
		case spk::Keyboard::Key::F7:
			return ("F7");
		case spk::Keyboard::Key::F8:
			return ("F8");
		case spk::Keyboard::Key::F9:
			return ("F9");
		case spk::Keyboard::Key::F10:
			return ("F10");
		case spk::Keyboard::Key::F11:
			return ("F11");
		case spk::Keyboard::Key::F12:
			return ("F12");
		case spk::Keyboard::Key::F13:
			return ("F13");
		case spk::Keyboard::Key::F14:
			return ("F14");
		case spk::Keyboard::Key::F15:
			return ("F15");
		case spk::Keyboard::Key::F16:
			return ("F16");
		case spk::Keyboard::Key::F17:
			return ("F17");
		case spk::Keyboard::Key::F18:
			return ("F18");
		case spk::Keyboard::Key::F19:
			return ("F19");
		case spk::Keyboard::Key::F20:
			return ("F20");
		case spk::Keyboard::Key::F21:
			return ("F21");
		case spk::Keyboard::Key::F22:
			return ("F22");
		case spk::Keyboard::Key::F23:
			return ("F23");
		case spk::Keyboard::Key::F24:
			return ("F24");
		case spk::Keyboard::Key::NumLock:
			return ("NumLock");
		case spk::Keyboard::Key::Scroll:
			return ("Scroll");
		case spk::Keyboard::Key::LeftShift:
			return ("LeftShift");
		case spk::Keyboard::Key::RightShift:
			return ("RightShift");
		case spk::Keyboard::Key::LeftControl:
			return ("LeftControl");
		case spk::Keyboard::Key::RightControl:
			return ("RightControl");
		case spk::Keyboard::Key::LeftMenu:
			return ("LeftMenu");
		case spk::Keyboard::Key::RightMenu:
			return ("RightMenu");
		case spk::Keyboard::Key::SemiColon:
			return ("SemiColon");
		case spk::Keyboard::Key::Plus:
			return ("Plus");
		case spk::Keyboard::Key::Comma:
			return ("Comma");
		case spk::Keyboard::Key::Minus:
			return ("Minus");
		case spk::Keyboard::Key::Period:
			return ("Period");
		case spk::Keyboard::Key::QuestionMark:
			return ("QuestionMark");
		case spk::Keyboard::Key::Tilde:
			return ("Tilde");
		case spk::Keyboard::Key::LeftBracket:
			return ("LeftBracket");
		case spk::Keyboard::Key::VerticalLine:
			return ("VerticalLine");
		case spk::Keyboard::Key::RightBracket:
			return ("RightBracket");
		case spk::Keyboard::Key::Quote:
			return ("Quote");
		case spk::Keyboard::Key::Unknown:
			return ("Unknown");
		case spk::Keyboard::Key::AngleBracket:
			return ("AngleBracket");
		case spk::Keyboard::Key::Process:
			return ("Process");
		default:
			return ("Unknown key");
		}
	}

	std::wstring toWstring(const Keyboard::Key &p_key)
	{
		switch (p_key)
		{
		case spk::Keyboard::Key::Backspace:
			return (L"Backspace");
		case spk::Keyboard::Key::Tab:
			return (L"Tab");
		case spk::Keyboard::Key::Clear:
			return (L"Clear");
		case spk::Keyboard::Key::Return:
			return (L"Return");
		case spk::Keyboard::Key::Shift:
			return (L"Shift");
		case spk::Keyboard::Key::Control:
			return (L"Control");
		case spk::Keyboard::Key::Alt:
			return (L"Alt");
		case spk::Keyboard::Key::Pause:
			return (L"Pause");
		case spk::Keyboard::Key::Capslock:
			return (L"Capslock");
		case spk::Keyboard::Key::Escape:
			return (L"Escape");
		case spk::Keyboard::Key::Convert:
			return (L"Convert");
		case spk::Keyboard::Key::Non_convert:
			return (L"Non_convert");
		case spk::Keyboard::Key::Accept:
			return (L"Accept");
		case spk::Keyboard::Key::Mode_change:
			return (L"Mode_change");
		case spk::Keyboard::Key::Space:
			return (L"Space");
		case spk::Keyboard::Key::Prior:
			return (L"Prior");
		case spk::Keyboard::Key::Next:
			return (L"Next");
		case spk::Keyboard::Key::End:
			return (L"End");
		case spk::Keyboard::Key::Home:
			return (L"Home");
		case spk::Keyboard::Key::LeftArrow:
			return (L"LeftArrow");
		case spk::Keyboard::Key::UpArrow:
			return (L"UpArrow");
		case spk::Keyboard::Key::RightArrow:
			return (L"RightArrow");
		case spk::Keyboard::Key::DownArrow:
			return (L"DownArrow");
		case spk::Keyboard::Key::Select:
			return (L"Select");
		case spk::Keyboard::Key::Print:
			return (L"Print");
		case spk::Keyboard::Key::Execute:
			return (L"Execute");
		case spk::Keyboard::Key::Snapshot:
			return (L"Snapshot");
		case spk::Keyboard::Key::Insert:
			return (L"Insert");
		case spk::Keyboard::Key::Delete:
			return (L"Delete");
		case spk::Keyboard::Key::Help:
			return (L"Help");
		case spk::Keyboard::Key::Key0:
			return (L"Key0");
		case spk::Keyboard::Key::Key1:
			return (L"Key1");
		case spk::Keyboard::Key::Key2:
			return (L"Key2");
		case spk::Keyboard::Key::Key3:
			return (L"Key3");
		case spk::Keyboard::Key::Key4:
			return (L"Key4");
		case spk::Keyboard::Key::Key5:
			return (L"Key5");
		case spk::Keyboard::Key::Key6:
			return (L"Key6");
		case spk::Keyboard::Key::Key7:
			return (L"Key7");
		case spk::Keyboard::Key::Key8:
			return (L"Key8");
		case spk::Keyboard::Key::Key9:
			return (L"Key9");
		case spk::Keyboard::Key::A:
			return (L"A");
		case spk::Keyboard::Key::B:
			return (L"B");
		case spk::Keyboard::Key::C:
			return (L"C");
		case spk::Keyboard::Key::D:
			return (L"D");
		case spk::Keyboard::Key::E:
			return (L"E");
		case spk::Keyboard::Key::F:
			return (L"F");
		case spk::Keyboard::Key::G:
			return (L"G");
		case spk::Keyboard::Key::H:
			return (L"H");
		case spk::Keyboard::Key::I:
			return (L"I");
		case spk::Keyboard::Key::J:
			return (L"J");
		case spk::Keyboard::Key::K:
			return (L"K");
		case spk::Keyboard::Key::L:
			return (L"L");
		case spk::Keyboard::Key::M:
			return (L"M");
		case spk::Keyboard::Key::N:
			return (L"N");
		case spk::Keyboard::Key::O:
			return (L"O");
		case spk::Keyboard::Key::P:
			return (L"P");
		case spk::Keyboard::Key::Q:
			return (L"Q");
		case spk::Keyboard::Key::R:
			return (L"R");
		case spk::Keyboard::Key::S:
			return (L"S");
		case spk::Keyboard::Key::T:
			return (L"T");
		case spk::Keyboard::Key::U:
			return (L"U");
		case spk::Keyboard::Key::V:
			return (L"V");
		case spk::Keyboard::Key::W:
			return (L"W");
		case spk::Keyboard::Key::X:
			return (L"X");
		case spk::Keyboard::Key::Y:
			return (L"Y");
		case spk::Keyboard::Key::Z:
			return (L"Z");
		case spk::Keyboard::Key::LeftWindows:
			return (L"LeftWindows");
		case spk::Keyboard::Key::RightWindows:
			return (L"RightWindows");
		case spk::Keyboard::Key::App:
			return (L"App");
		case spk::Keyboard::Key::Sleep:
			return (L"Sleep");
		case spk::Keyboard::Key::Numpad0:
			return (L"Numpad0");
		case spk::Keyboard::Key::Numpad1:
			return (L"Numpad1");
		case spk::Keyboard::Key::Numpad2:
			return (L"Numpad2");
		case spk::Keyboard::Key::Numpad3:
			return (L"Numpad3");
		case spk::Keyboard::Key::Numpad4:
			return (L"Numpad4");
		case spk::Keyboard::Key::Numpad5:
			return (L"Numpad5");
		case spk::Keyboard::Key::Numpad6:
			return (L"Numpad6");
		case spk::Keyboard::Key::Numpad7:
			return (L"Numpad7");
		case spk::Keyboard::Key::Numpad8:
			return (L"Numpad8");
		case spk::Keyboard::Key::Numpad9:
			return (L"Numpad9");
		case spk::Keyboard::Key::NumpadMultiply:
			return (L"NumpadMultiply");
		case spk::Keyboard::Key::NumpadPlus:
			return (L"NumpadPlus");
		case spk::Keyboard::Key::NumpadSeparator:
			return (L"NumpadSeparator");
		case spk::Keyboard::Key::NumpadMinus:
			return (L"NumpadMinus");
		case spk::Keyboard::Key::NumpadDecimal:
			return (L"NumpadDecimal");
		case spk::Keyboard::Key::NumpadDivide:
			return (L"NumpadDivide");
		case spk::Keyboard::Key::F1:
			return (L"F1");
		case spk::Keyboard::Key::F2:
			return (L"F2");
		case spk::Keyboard::Key::F3:
			return (L"F3");
		case spk::Keyboard::Key::F4:
			return (L"F4");
		case spk::Keyboard::Key::F5:
			return (L"F5");
		case spk::Keyboard::Key::F6:
			return (L"F6");
		case spk::Keyboard::Key::F7:
			return (L"F7");
		case spk::Keyboard::Key::F8:
			return (L"F8");
		case spk::Keyboard::Key::F9:
			return (L"F9");
		case spk::Keyboard::Key::F10:
			return (L"F10");
		case spk::Keyboard::Key::F11:
			return (L"F11");
		case spk::Keyboard::Key::F12:
			return (L"F12");
		case spk::Keyboard::Key::F13:
			return (L"F13");
		case spk::Keyboard::Key::F14:
			return (L"F14");
		case spk::Keyboard::Key::F15:
			return (L"F15");
		case spk::Keyboard::Key::F16:
			return (L"F16");
		case spk::Keyboard::Key::F17:
			return (L"F17");
		case spk::Keyboard::Key::F18:
			return (L"F18");
		case spk::Keyboard::Key::F19:
			return (L"F19");
		case spk::Keyboard::Key::F20:
			return (L"F20");
		case spk::Keyboard::Key::F21:
			return (L"F21");
		case spk::Keyboard::Key::F22:
			return (L"F22");
		case spk::Keyboard::Key::F23:
			return (L"F23");
		case spk::Keyboard::Key::F24:
			return (L"F24");
		case spk::Keyboard::Key::NumLock:
			return (L"NumLock");
		case spk::Keyboard::Key::Scroll:
			return (L"Scroll");
		case spk::Keyboard::Key::LeftShift:
			return (L"LeftShift");
		case spk::Keyboard::Key::RightShift:
			return (L"RightShift");
		case spk::Keyboard::Key::LeftControl:
			return (L"LeftControl");
		case spk::Keyboard::Key::RightControl:
			return (L"RightControl");
		case spk::Keyboard::Key::LeftMenu:
			return (L"LeftMenu");
		case spk::Keyboard::Key::RightMenu:
			return (L"RightMenu");
		case spk::Keyboard::Key::SemiColon:
			return (L"SemiColon");
		case spk::Keyboard::Key::Plus:
			return (L"Plus");
		case spk::Keyboard::Key::Comma:
			return (L"Comma");
		case spk::Keyboard::Key::Minus:
			return (L"Minus");
		case spk::Keyboard::Key::Period:
			return (L"Period");
		case spk::Keyboard::Key::QuestionMark:
			return (L"QuestionMark");
		case spk::Keyboard::Key::Tilde:
			return (L"Tilde");
		case spk::Keyboard::Key::LeftBracket:
			return (L"LeftBracket");
		case spk::Keyboard::Key::VerticalLine:
			return (L"VerticalLine");
		case spk::Keyboard::Key::RightBracket:
			return (L"RightBracket");
		case spk::Keyboard::Key::Quote:
			return (L"Quote");
		case spk::Keyboard::Key::Unknown:
			return (L"Unknown");
		case spk::Keyboard::Key::AngleBracket:
			return (L"AngleBracket");
		case spk::Keyboard::Key::Process:
			return (L"Process");
		default:
			return (L"Unknown key");
		}
	}

	std::ostream &operator<<(std::ostream &p_stream, const Keyboard::Key &p_key)
	{
		p_stream << toString(p_key);
		return p_stream;
	}

	std::wostream &operator<<(std::wostream &p_stream, const Keyboard::Key &p_key)
	{
		p_stream << toWstring(p_key);
		return p_stream;
	}
}
