#pragma once

// Traits & utilities
#include "structures/container/spk_binary_field.hpp"
#include "structures/container/spk_cached_data.hpp"
#include "structures/container/spk_flags.hpp"
#include "structures/container/spk_object_pool.hpp"
#include "structures/container/spk_observable_value.hpp"
#include "structures/design_pattern/spk_activable_trait.hpp"
#include "structures/design_pattern/spk_blockable_trait.hpp"
#include "structures/design_pattern/spk_contract_provider.hpp"
#include "structures/design_pattern/spk_inherence_trait.hpp"
#include "structures/design_pattern/spk_synchronizable_trait.hpp"
#include "structures/graphics/geometry/spk_color.hpp"
#include "structures/system/thread/spk_thread_safe_contract.hpp"
#include "structures/system/thread/spk_thread_safe_deque.hpp"
#include "type/spk_concepts.hpp"
#include "type/spk_constants.hpp"

// Math & geometry
#include "structures/graphics/geometry/spk_mesh.hpp"
#include "structures/math/spk_approx_value.hpp"
#include "structures/math/spk_matrix.hpp"
#include "structures/math/spk_quaternion.hpp"
#include "structures/math/spk_rect_2d.hpp"
#include "structures/math/spk_vector2.hpp"
#include "structures/math/spk_vector3.hpp"
#include "structures/math/spk_vector4.hpp"
#include "utils/spk_math.hpp"

// Time
#include "structures/system/event/spk_update_tick.hpp"
#include "structures/system/time/spk_chronometer.hpp"
#include "structures/system/time/spk_duration.hpp"
#include "structures/system/time/spk_timer.hpp"
#include "structures/system/time/spk_timestamp.hpp"
#include "type/spk_time_unit.hpp"
#include "utils/spk_time_utils.hpp"

// Input
#include "structures/system/device/input/spk_keyboard.hpp"
#include "structures/system/device/input/spk_mouse.hpp"
#include "structures/system/event/spk_events.hpp"
#include "type/spk_input_state.hpp"

// Platform / GPU runtime interfaces
#include "structures/graphics/opengl/spk_opengl_render_context.hpp"
#include "structures/graphics/rendering/context/spk_render_context.hpp"
#include "structures/system/device/runtime/spk_opengl_runtime.hpp"
#include "structures/system/device/runtime/spk_platform_runtime.hpp"
#include "structures/system/device/window/spk_frame.hpp"
#include "structures/system/device/window/spk_surface_state.hpp"
#include "structures/system/win32/spk_winapi_class.hpp"
#include "structures/system/win32/spk_winapi_cursor.hpp"
#include "structures/system/win32/spk_winapi_frame.hpp"
#include "structures/system/win32/spk_winapi_platform_runtime.hpp"
#include "structures/system/win32/spk_winapi_window.hpp"

// Rendering
#include "structures/application/module/spk_render_module.hpp"
#include "structures/graphics/geometry/spk_color_mesh_2d.hpp"
#include "structures/graphics/geometry/spk_generic_mesh.hpp"
#include "structures/graphics/geometry/spk_mesh_2d.hpp"
#include "structures/graphics/geometry/spk_texture_mesh_2d.hpp"
#include "structures/graphics/opengl/spk_opengl_clear_command.hpp"
#include "structures/graphics/opengl/spk_opengl_draw_arrays_command.hpp"
#include "structures/graphics/opengl/spk_opengl_draw_elements_command.hpp"
#include "structures/graphics/opengl/spk_opengl_draw_elements_instanced_command.hpp"
#include "structures/graphics/rendering/command/spk_color_rectangle_render_command.hpp"
#include "structures/graphics/rendering/command/spk_draw_color_mesh_render_command.hpp"
#include "structures/graphics/rendering/command/spk_draw_font_render_command.hpp"
#include "structures/graphics/rendering/command/spk_draw_texture_mesh_render_command.hpp"
#include "structures/graphics/rendering/command/spk_image_render_command.hpp"
#include "structures/graphics/rendering/command/spk_nine_slice_render_command.hpp"
#include "structures/graphics/rendering/command/spk_render_command.hpp"
#include "structures/graphics/rendering/command/spk_sprite_render_command.hpp"
#include "structures/graphics/rendering/command/spk_text_render_command.hpp"
#include "structures/graphics/rendering/command/spk_viewport_render_command.hpp"
#include "structures/graphics/rendering/snapshot/spk_render_snapshot.hpp"
#include "structures/graphics/rendering/snapshot/spk_render_snapshot_builder.hpp"
#include "structures/graphics/rendering/unit/spk_render_unit.hpp"
#include "structures/graphics/rendering/unit/spk_render_unit_builder.hpp"
#include "structures/graphics/spk_buffer_object.hpp"
#include "structures/graphics/spk_gpu_data_buffer_center.hpp"
#include "structures/graphics/spk_index_buffer_object.hpp"
#include "structures/graphics/spk_layout_buffer_object.hpp"
#include "structures/graphics/spk_primitive.hpp"
#include "structures/graphics/spk_program.hpp"
#include "structures/graphics/spk_sampler_object.hpp"
#include "structures/graphics/spk_shader_storage_buffer_object.hpp"
#include "structures/graphics/spk_uniform.hpp"
#include "structures/graphics/spk_uniform_buffer_object.hpp"
#include "structures/graphics/spk_vertex_array_object.hpp"
#include "structures/graphics/spk_vertex_buffer_object.hpp"
#include "structures/graphics/texture/spk_font.hpp"
#include "structures/graphics/texture/spk_image.hpp"
#include "structures/graphics/texture/spk_sprite_sheet.hpp"

// Modules
#include "structures/application/module/spk_frame_module.hpp"
#include "structures/application/module/spk_keyboard_module.hpp"
#include "structures/application/module/spk_module.hpp"
#include "structures/application/module/spk_mouse_module.hpp"
#include "structures/application/module/spk_update_module.hpp"

// Widget system
#include "structures/widget/spk_action_bar.hpp"
#include "structures/widget/spk_animation_label.hpp"
#include "structures/widget/spk_checkable_icon_button.hpp"
#include "structures/widget/spk_command_panel.hpp"
#include "structures/widget/spk_container_widget.hpp"
#include "structures/widget/spk_debug_overlay.hpp"
#include "structures/widget/spk_dynamic_text_label.hpp"
#include "structures/widget/spk_form_layout.hpp"
#include "structures/widget/spk_grid_layout.hpp"
#include "structures/widget/spk_icon_button.hpp"
#include "structures/widget/spk_image_label.hpp"
#include "structures/widget/spk_interface_window.hpp"
#include "structures/widget/spk_layout.hpp"
#include "structures/widget/spk_linear_layout.hpp"
#include "structures/widget/spk_message_box.hpp"
#include "structures/widget/spk_numeric_spin_box.hpp"
#include "structures/widget/spk_panel.hpp"
#include "structures/widget/spk_prompt_panel.hpp"
#include "structures/widget/spk_push_button.hpp"
#include "structures/widget/spk_resizable_element.hpp"
#include "structures/widget/spk_scalable_widget.hpp"
#include "structures/widget/spk_screen.hpp"
#include "structures/widget/spk_scroll_area.hpp"
#include "structures/widget/spk_scroll_bar.hpp"
#include "structures/widget/spk_slider_bar.hpp"
#include "structures/widget/spk_spacer_widget.hpp"
#include "structures/widget/spk_spin_box.hpp"
#include "structures/widget/spk_text_area.hpp"
#include "structures/widget/spk_text_edit.hpp"
#include "structures/widget/spk_text_label.hpp"
#include "structures/widget/spk_widget.hpp"
#include "structures/widget/spk_widget_style.hpp"
#include "structures/widget/spk_workspace.hpp"
#include "type/spk_orientation.hpp"

// Window & application
#include "structures/application/spk_application.hpp"
#include "structures/system/device/window/spk_window.hpp"
#include "structures/system/device/window/spk_window_handle.hpp"
#include "structures/system/device/window/spk_window_host.hpp"
#include "structures/system/device/window/spk_window_registry.hpp"
