#pragma once

// Traits & utilities
#include "structures/design_pattern/spk_activable_trait.hpp"
#include "structures/container/spk_binary_field.hpp"
#include "structures/design_pattern/spk_blockable_trait.hpp"
#include "structures/container/spk_cached_data.hpp"
#include "type/spk_concepts.hpp"
#include "type/spk_constants.hpp"
#include "structures/design_pattern/spk_contract_provider.hpp"
#include "structures/graphics/geometry/spk_color.hpp"
#include "structures/container/spk_flags.hpp"
#include "structures/design_pattern/spk_inherence_trait.hpp"
#include "structures/container/spk_object_pool.hpp"
#include "structures/container/spk_observable_value.hpp"
#include "structures/design_pattern/spk_synchronizable_trait.hpp"
#include "structures/system/thread/spk_thread_safe_contract.hpp"
#include "structures/system/thread/spk_thread_safe_deque.hpp"

// Math & geometry
#include "structures/math/spk_approx_value.hpp"
#include "utils/spk_math.hpp"
#include "structures/math/spk_rect_2d.hpp"
#include "structures/math/spk_matrix.hpp"
#include "structures/graphics/geometry/spk_mesh.hpp"
#include "structures/math/spk_vector2.hpp"
#include "structures/math/spk_vector3.hpp"
#include "structures/math/spk_vector4.hpp"
#include "structures/math/spk_quaternion.hpp"

// Time
#include "structures/system/time/spk_chronometer.hpp"
#include "structures/system/time/spk_duration.hpp"
#include "structures/system/time/spk_timer.hpp"
#include "structures/system/time/spk_timestamp.hpp"
#include "type/spk_time_unit.hpp"
#include "utils/spk_time_utils.hpp"
#include "structures/system/event/spk_update_tick.hpp"

// Input
#include "type/spk_input_state.hpp"
#include "structures/system/device/input/spk_keyboard.hpp"
#include "structures/system/device/input/spk_mouse.hpp"
#include "structures/system/event/spk_events.hpp"

// Platform / GPU runtime interfaces
#include "structures/system/device/window/spk_surface_state.hpp"
#include "structures/system/device/window/spk_frame.hpp"
#include "structures/system/device/runtime/spk_platform_runtime.hpp"
#include "structures/graphics/rendering/context/spk_render_context.hpp"
#include "structures/system/device/runtime/spk_opengl_runtime.hpp"
#ifdef _WIN32
#include "structures/system/win32/spk_winapi_class.hpp"
#include "structures/system/win32/spk_winapi_cursor.hpp"
#include "structures/system/win32/spk_winapi_window.hpp"
#include "structures/system/win32/spk_winapi_frame.hpp"
#include "structures/system/win32/spk_winapi_platform_runtime.hpp"
#include "structures/graphics/opengl/spk_opengl_render_context.hpp"
#endif

// Rendering
#include "structures/graphics/rendering/command/spk_render_command.hpp"
#include "structures/graphics/rendering/command/spk_draw_color_mesh_render_command.hpp"
#include "structures/graphics/rendering/command/spk_draw_font_render_command.hpp"
#include "structures/graphics/rendering/command/spk_draw_texture_mesh_render_command.hpp"
#include "structures/graphics/rendering/command/spk_color_rectangle_render_command.hpp"
#include "structures/graphics/rendering/command/spk_image_render_command.hpp"
#include "structures/graphics/rendering/command/spk_nine_slice_render_command.hpp"
#include "structures/graphics/rendering/command/spk_sprite_render_command.hpp"
#include "structures/graphics/rendering/command/spk_text_render_command.hpp"
#include "structures/graphics/rendering/unit/spk_render_unit.hpp"
#include "structures/graphics/rendering/unit/spk_render_unit_builder.hpp"
#include "structures/graphics/rendering/snapshot/spk_render_snapshot.hpp"
#include "structures/graphics/rendering/snapshot/spk_render_snapshot_builder.hpp"
#include "structures/application/module/spk_render_module.hpp"
#include "structures/graphics/geometry/spk_generic_mesh.hpp"
#include "structures/graphics/geometry/spk_mesh_2d.hpp"
#include "structures/graphics/geometry/spk_color_mesh_2d.hpp"
#include "structures/graphics/geometry/spk_texture_mesh_2d.hpp"
#include "structures/graphics/texture/spk_font.hpp"
#include "structures/graphics/texture/spk_image.hpp"
#include "structures/graphics/texture/spk_sprite_sheet.hpp"
#include "structures/graphics/opengl/spk_opengl_program.hpp"
#include "structures/graphics/opengl/spk_opengl_buffer_object.hpp"
#include "structures/graphics/opengl/spk_opengl_clear_command.hpp"
#include "structures/graphics/opengl/spk_opengl_draw_arrays_command.hpp"
#include "structures/graphics/opengl/spk_opengl_draw_elements_command.hpp"
#include "structures/graphics/opengl/spk_opengl_draw_elements_instanced_command.hpp"
#include "structures/graphics/opengl/spk_opengl_gpu_data_buffer_center.hpp"
#include "structures/graphics/opengl/spk_opengl_index_buffer_object.hpp"
#include "structures/graphics/opengl/spk_opengl_layout_buffer_object.hpp"
#include "type/spk_opengl_primitive.hpp"
#include "structures/graphics/opengl/spk_opengl_shader_storage_buffer_object.hpp"
#include "structures/graphics/opengl/spk_opengl_uniform.hpp"
#include "structures/graphics/opengl/spk_opengl_uniform_buffer_object.hpp"
#include "structures/graphics/opengl/spk_opengl_vertex_array_object.hpp"
#include "structures/graphics/opengl/spk_opengl_vertex_buffer_object.hpp"
#include "structures/graphics/rendering/command/spk_viewport_render_command.hpp"

// Modules
#include "structures/application/module/spk_module.hpp"
#include "structures/application/module/spk_frame_module.hpp"
#include "structures/application/module/spk_keyboard_module.hpp"
#include "structures/application/module/spk_mouse_module.hpp"
#include "structures/application/module/spk_update_module.hpp"

// Widget system
#include "structures/widget/spk_panel.hpp"
#include "structures/widget/spk_push_button.hpp"
#include "structures/widget/spk_text_label.hpp"
#include "structures/widget/spk_widget.hpp"
#include "structures/widget/spk_widget_style.hpp"

// Window & application
#include "structures/system/device/window/spk_window_host.hpp"
#include "structures/system/device/window/spk_window_handle.hpp"
#include "structures/system/device/window/spk_window.hpp"
#include "structures/system/device/window/spk_window_registry.hpp"
#include "structures/application/spk_application.hpp"
